name: CVE Scanning for Docker

on:
  push:
    paths:
      - 'docker/**/Dockerfile'
      - '.github/workflows/cve-scanning.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder-name: ["aws-linux", "el7", "el8", "ubuntu-focal-deb", "ubuntu-focal" ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@1.0.11
      - name: Build
        run: docker build -f Dockerfile -t user/${{ matrix.folder-name }}:latest .
        working-directory: docker/${{ matrix.folder-name }}
      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: user/${{ matrix.folder-name }}:latest
          --security-checks vuln
        env:
          TRIVY_TIMEOUT: 20m
